name: nancy_file_share
description: A futuristic file sharing app with gesture and animation.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  lottie: ^3.1.0
  permission_handler: ^11.0.1
  video_player: ^2.7.0
  camera: ^0.10.5+2
  google_mlkit_hand_detection: ^0.3.0
  provider: ^6.1.1
  flutter_nearby_connections: ^1.3.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/crunch_animation.json
    - assets/animations/send_particles.json
    - assets/animations/receive_portal.json
    - assets/videos/waiting_receive.mp4
    - assets/images/logo.png
