name: Flutter Create and Push Android Folder

on:
  push:
    branches:
      - main
    paths:
      - trigger-flutter-create.txt  # triggers only when this file is pushed (optional safety)

jobs:
  generate:
    name: Generate Flutter Android Folder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'  # or latest stable

      - name: Run Flutter Create (Preserve lib/)
        run: |
          mkdir temp
          cp -r lib pubspec.yaml temp/ 2>/dev/null || true
          flutter create .
          rm -rf lib
          cp -r temp/lib lib
          cp temp/pubspec.yaml pubspec.yaml
          rm -rf temp

      - name: Push Generated Files (android/, ios/, etc.)
        run: |
          git config user.name "flutter-bot"
          git config user.email "bot@flutter.dev"
          git add .
          git commit -m "🚀 Auto-generated Flutter structure (including android/)"
          git push
