name: Build Flutter APK

on:
  push:
    branches:
      - main  # or 'master' depending on your branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # use latest stable or your preferred

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Android Licensing (for Android SDK)
        run: yes | sdkmanager --licenses || true

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NancyFileShare-APK
          path: build/app/outputs/flutter-apk/app-release.apk
